language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
script:
  - set -e
  - mvn clean site -Psite --errors --batch-mode
  - mvn clean install -Pqulice --errors --batch-mode
after_success:
  - bash <(curl -s https://codecov.io/bash)