# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: license-copyright
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  license-copyright:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check copyright header
        # yamllint disable-line rule:line-length
        uses: yegor256/copyrights-action@4f3f2089561282bd83172896a8c9ceb5f936bd00
        with:
          ignore: >-
            **/*.properties
            **/*.yml
