# SPDX-FileCopyrightText: Copyright (C) 2017-2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-build
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  java-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Maven in Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y maven
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build project in Unix/macOS
        if: runner.os != 'Windows'
        run: |
          if [ -x "mvnw" ]; then
            MVN="./mvnw"
          else
            MVN=mvn
          fi
          if grep -q "<id>qulice</id>" pom.xml; then
            $MVN --errors --batch-mode clean install -Pqulice
          else
            $MVN --errors --batch-mode clean install
          fi
      - name: Build project in Windows
        if: runner.os == 'Windows'
        # yamllint disable rule:line-length
        run: |
          for /f "delims=" %%i in ('findstr "<id>qulice</id>" pom.xml') do set qulice=1
          if exist "mvnw.cmd" (
            if defined qulice (
              mvnw.cmd --errors --batch-mode clean install -Pqulice
            ) else (
              mvnw.cmd --errors --batch-mode clean install
            )
          ) else (
            if defined qulice (
              mvn --errors --batch-mode clean install -Pqulice
            ) else (
              mvn --errors --batch-mode clean install
            )
          )
        # yamllint enable rule:line-length
        shell: cmd
