# SPDX-FileCopyrightText: Copyright (C) 2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: java-build
'on':
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
defaults:
  run:
    shell: bash -xeuo pipefail {0}
permissions:
  contents: read
jobs:
  java-linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Configure apt cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install dependencies
        run: |
          sudo apt-get update
          [ -f apt-packages.txt ] && xargs -a apt-packages.txt \
            sudo apt-get install -y --no-install-recommends
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build project
        # yamllint disable rule:line-length
        run: |
          # Choose maven embedded or system
          [ -x "mvnw" ] && MVN="./mvnw" || MVN="mvn"

          # If exist qulice profile, execute using it
          PROFILE=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice" || echo "")
          $MVN --errors --batch-mode clean install "${PROFILE}"
        # yamllint enable rule:line-length
  java-macos-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install maven
        run: |
          brew update
          brew install maven
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build project
        # yamllint disable rule:line-length
        run: |
          # Choose maven embedded or system
          [ -x "mvnw" ] && MVN="./mvnw" || MVN="mvn"

          # If exist qulice profile, execute using it
          PROFILE=$(grep -q "<id>qulice</id>" pom.xml && echo "-Pqulice" || echo "")
          $MVN --errors --batch-mode clean install "${PROFILE}"
        # yamllint enable rule:line-length
  java-windows-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        java: [11, 17, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install maven
        run: |
          choco install -y maven
      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build project
        # yamllint disable rule:line-length
        run: |
          @echo off
          for /f "delims=" %%i in ('findstr "<id>qulice</id>" pom.xml') do set "Q=1"
          if exist "mvnw.cmd" (set "M=mvnw.cmd") else (set "M=mvn")
          %M% --errors --batch-mode clean install %Q:~-2,-1%-Pqulice
        # yamllint enable rule:line-length
        shell: cmd
