# SPDX-FileCopyrightText: Copyright (C) 2017-2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: license-copyright
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  license-copyright:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check copyright header
        uses: yegor256/copyrights-action@0.0.12
        with:
          ignore: >-
            **/*.properties
