# SPDX-FileCopyrightText: Copyright (C) 2017-2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: markdown-lint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
