# SPDX-FileCopyrightText: Copyright (C) 2017-2025 Fabrício Barros Cabral
# SPDX-License-Identifier: MIT
---
name: typos
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check files for typos
        uses: crate-ci/typos@v1.35.5
